[versions]
aws-lambda-core = "1.4.0"
aws-lambda-events = "3.16.1"
dynamodb = "2.54.7"
gson = "2.14.0"

[libraries]
aws-lambda-core = { group = "com.amazonaws", name = "aws-lambda-java-core", version.ref = "aws-lambda-core" }
aws-lambda-events = { group = "com.amazonaws", name = "aws-lambda-java-events", version.ref = "aws-lambda-events" }
dynamodb= { group = "software.amazon.awssdk", name = "dynamodb-enhanced", version.ref = "dynamodb" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }